# Generated by Django 3.0 on 2020-04-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.CharField(choices=[('0', 'Novice'), ('1', 'Advanced Beginner'), ('2', 'Competent'), ('3', 'Proficient'), ('4', 'Expert')], default='0', max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(default='question empty')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Answer')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Level')),
            ],
        ),
    ]
