# Generated by Django 3.0 on 2020-04-03 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=121)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('kind_post', models.CharField(choices=[('MR', 'Must Read'), ('RS', 'Read Slowly'), ('FF', 'Fun Fact')], default='MR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=37, unique=True)),
            ],
        ),
    ]
