# Generated by Django 3.0 on 2020-04-12 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=121)),
                ('slug', models.SlugField(unique=True)),
                ('published', models.DateField(default=django.utils.timezone.now)),
                ('kind_post', models.CharField(choices=[('MR', 'Must Read'), ('RS', 'Read Slowly'), ('FF', 'Fun Fact')], default='MR', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
