# Generated by Django 3.0 on 2020-04-12 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200412_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(default=datetime.date(2020, 4, 12)),
        ),
    ]
