# Generated by Django 3.0 on 2020-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200412_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='kind_post',
            new_name='kind_article',
        ),
    ]
